import type { Metadata } from "next";
import { Lexend, Poppins } from "next/font/google";
import "./globals.css";

const lexendFont = Lexend({
    variable: "--font-lexend",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const poppinsFont = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Lawny app",
    description: "Generated by Lawyn template",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${lexendFont.variable} ${poppinsFont.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
